backend:
  name: github
  repo: doradosystemsro/servicepclaptop
  branch: main
  base_url: https://decap-cms-oauth.vercel.app # Proxy stabil gratuit pentru autentificare GitHub
  auth_endpoint: /auth

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "Articole Blog"
    folder: "blog"
    extension: "html"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titlu", name: "title", widget: "string" }
      - { label: "Corp Articol (HTML)", name: "body", widget: "code", default_language: "html" }
